CREATE TABLE Users(
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
hased_password VARCHAR(255) NOT NULL
);

CREATE TABLE Tweet (
id INT NOT NULL AUTO_INCREMENT,
userID int NOT NULL,
text VARCHAR(255) NOT NULL,
creationDate DATE,
PRIMARY KEY(ID),
FOREIGN KEY(userID)
REFERENCES Users(id)
);
